# Generated by Django 4.1.7 on 2023-03-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0002_job_description_job_location_alter_job_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_published',
        ),
        migrations.AddField(
            model_name='job',
            name='related_keywords',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
